project:
  type: website
  output-dir: docs
  resources: curriculo.pdf

website:
  title: "" #Portfolio
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projetos.qmd
  favicon: snoopyicon.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true



