project:
  type: website
  output-dir: docs
  resources: 
    - galeria/
    - arquivos/

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projetos.qmd
        text: Projetos
  favicon: galeria/snoopyicon.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true



